# Basic configuration for static site
[build]
  publish = "build"  # Changed to use the build directory
  command = "npm install && npm run build"  # Install dependencies and run build script

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
