[build]
  command = "npm run build"
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--no-package-lock"
  NPM_VERBOSE = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#custom"
  targetPort = 8888
  autoLaunch = true
  publish = "public"
