[build]
  command = "npm run build"
  publish = "public"
  functions = "functions"

[build.environment]
  NPM_FLAGS = "--no-package-lock"
  NPM_VERBOSE = "true"
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    functions = "functions"
    publish = "public"
