[build]
  command = "npm run build"
  publish = "public"
  functions = "functions"

[build.environment]
  NPM_FLAGS = "--no-package-lock"
  NPM_VERBOSE = "true"
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW-FROM https://expense-tracker-2048.streamlit.app"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[dev]
  framework = "#custom"
  targetPort = 8888
  autoLaunch = true
  publish = "public"
